using MATLAB
using JLD2
using Printf

# ? shell making process which run comparison code parallelly

runN = 50;

kbq = 0.025;

j2Grid_c = 0.00:0.01:0.30;  j2len = length(j2Grid_c);
j3Grid_c = 0.00:0.01:0.20;  j3len = length(j3Grid_c);
jcGrid_c = 0.80;            jclen = length(jcGrid_c);

jtotlen = j2len*j3len*jclen;

eachrun = round(Int64,jtotlen/runN);

fid = open("autoCompare.sh", "w");

println(fid, "#!/bin/bash");
println(fid, "# you have to run this file in the same directory with local_minima_remover_D.jl");
println(fid, "# this file is automatically generated by local_minima_remover_C.jl");
println(fid, "# runN = $runN");
println(fid, "# jtotlen = $jtotlen");
println(fid, "# eachrun = $eachrun");


for idx = 1:runN
  sttN = 1 + (idx-1)*eachrun;
  if idx == runN
    endN = jtotlen;
  else
    endN = idx*eachrun;
  end
  
  strstr = @sprintf("local_minima_remover_D.jl %d %d %d", sttN, endN, idx);
  println(fid, "julia_wh $strstr &");
end

println(fid, "wait");
println(fid, "echo \"All done!\"");
println(fid, "exit 0");

close(fid)
